<?php
declare(strict_types=1);

namespace ScriptFUSION\Porter\Provider\Stripe\Connector;

use ScriptFUSION\Porter\Connector\DataSource;
use ScriptFUSION\Porter\Net\Http\HttpConnector;
use ScriptFUSION\Porter\Net\Http\HttpDataSource;
use ScriptFUSION\Porter\Net\Http\HttpResponse;

class StripeConnector extends HttpConnector
{
    private $apiKey;

    /**
     * @param string $apiKey
     */
    public function __construct($apiKey)
    {
        parent::__construct();

        $this->apiKey = $apiKey;
    }

    public function fetch(DataSource $source): HttpResponse
    {
        if (!$source instanceof HttpDataSource) {
            throw new \RuntimeException('Source must be of type: HttpDataSource.');
        }

        $source->addHeader('Authorization: Basic ' . base64_encode($this->apiKey));

        return parent::fetch($source); // TODO: Change the autogenerated stub
    }
}
